export interface CardData {
    id: string
    title: string
    description: string
    expanded: boolean
}

export const OVERVIEW_CARDS_DATA: CardData[] = [
    {
        id: 'tactical',
        title: 'Tactical Signals',
        description: 'See what to act on — right now.',
        expanded: false,
    },
    {
        id: 'market',
        title: 'Market Snapshot',
        description: "Understand how the market's moving today.",
        expanded: false,
    },
    {
        id: 'momentum',
        title: 'Momentum Alerts',
        description: 'Unfiltered alerts just as momentum builds.',
        expanded: false,
    },
    {
        id: 'allocation',
        title: 'Allocation View',
        description: "Know where you're positioned — and why it matters.",
        expanded: false,
    },
]

export const ALLOCATION_DATA_LIST = [
    {
        name: 'Equities',
        percentage: '45%',
        color: 'bg-lightgreen/10',
        border: 'border-lightgreen',
        desc: 'Raised exposure based on strong earnings momentum and improving macro data.',
    },
    {
        name: 'Crypto',
        percentage: '20%',
        color: 'bg-brown/10',
        border: 'border-brown',
        desc: 'Maintained current weight as BTC continues to respect key support and upside trend.',
    },
    {
        name: 'Fixed Income',
        percentage: '25%',
        color: 'bg-darkpurple/10',
        border: 'border-darkpurple',
        desc: 'Holding overweight position amid stable yields and defensive tilt in market sentiment.',
    },
    {
        name: 'Alternative',
        percentage: '10%',
        color: 'bg-mediumred/10',
        border: 'border-mediumred',
        desc: 'Reduced slightly to fund tactical increases in equities and crypto.',
    },
]

export const TACTICAL_SIGNALS_DATA_LIST = [
    {
        coin: 'Bitcoin',
        image: '/assets/dashboard/webp/graph1.webp',
        symbol: 'BTC',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'SPY',
        image: '/assets/dashboard/webp/graph2.webp',
        symbol: 'SPY',
        status: 'BUY',
        allocation: '10%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'QQQ',
        image: '/assets/dashboard/webp/graph3.webp',
        symbol: 'QQQ',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'SPY',
        image: '/assets/dashboard/webp/graph4.webp',
        symbol: 'SPY',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'Bitcoin',
        image: '/assets/dashboard/webp/graph1.webp',
        symbol: 'BTC',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'SPY',
        image: '/assets/dashboard/webp/graph2.webp',
        symbol: 'SPY',
        status: 'BUY',
        allocation: '10%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'QQQ',
        image: '/assets/dashboard/webp/graph3.webp',
        symbol: 'QQQ',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'SPY',
        image: '/assets/dashboard/webp/graph4.webp',
        symbol: 'SPY',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'Bitcoin',
        image: '/assets/dashboard/webp/graph1.webp',
        symbol: 'BTC',
        status: 'BUY',
        allocation: '15%',
        range: [420, 430],
        current: 425,
    },
    {
        coin: 'SPY',
        image: '/assets/dashboard/webp/graph2.webp',
        symbol: 'SPY',
        status: 'BUY',
        allocation: '10%',
        range: [420, 430],
        current: 425,
    },
]

export const MARKET_SNAPSHOT_DATA_LIST = [
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BULLISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'up',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BEARISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'down',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BULLISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'up',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BEARISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'down',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BULLISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'up',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BULLISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'up',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BEARISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'down',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BULLISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'up',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BEARISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'down',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BULLISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'up',
    },
    {
        name: 'Bitcoin',
        symbol: 'BTC',
        sentiment: 'BEARISH',
        comment: 'Low volume grind',
        percentage: '109%',
        status: '109%',
        trend: 'down',
    },
]

export const MOMENTUM_ALERTS_DATA_LIST = [
    {
        time: '10:32 AM',
        coin: 'BTC',
        trigger: 'Volume Surge',
        desc: 'BTC volume spiked 2x hourly avg — possible breakout.',
    },
    {
        time: '10:22 AM',
        coin: 'ETH',
        trigger: 'RSI Oversold (30)',
        desc: 'ETH may reverse — oversold levels seen on hourly RSI.',
    },
    {
        time: '10:32 AM',
        coin: 'SOL',
        trigger: 'MA Cross (10/50)',
        desc: 'Short-term bullish: 10DMA crossed above 50DMA.',
    },
    {
        time: '10:32 AM',
        coin: 'AVAX',
        trigger: 'Breakout ($38)',
        desc: 'AVAX volume spiked 2x hourly avg - possible breakout.',
    },
    {
        time: '10:32 AM',
        coin: 'BTC',
        trigger: 'Volume Surge',
        desc: 'BTC volume spiked 2x hourly avg — possible breakout.',
    },
    {
        time: '10:22 AM',
        coin: 'ETH',
        trigger: 'RSI Oversold (30)',
        desc: 'ETH may reverse — oversold levels seen on hourly RSI.',
    },
    {
        time: '10:32 AM',
        coin: 'SOL',
        trigger: 'MA Cross (10/50)',
        desc: 'Short-term bullish: 10DMA crossed above 50DMA.',
    },
    {
        time: '10:32 AM',
        coin: 'AVAX',
        trigger: 'Breakout ($38)',
        desc: 'AVAX volume spiked 2x hourly avg - possible breakout.',
    },
]
